Add support for new endpoint in ruby client [ch26459]
chartmogul/chartmogul-ruby pull request #96
Opened 2020-11-16 08:00 UTC by macharmi

2020-11-16 08:14 UTC, pkopac requested changes
You might want to add a test on the serialized JSON (careful about keys order, use [include](https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/include-matcher)).

2020-11-16 08:14 UTC, pkopac commented on lib/chartmogul/batch/import.rb
> +        cancellations.map(&:serialize_for_write)
```suggestion
        transactions.map(&:serialize_for_write)
```

2020-11-16 08:14 UTC, pkopac commented on lib/chartmogul/batch/import.rb
> +        cancellations.map(&:serialize_for_write)
```suggestion
        line_items.map(&:serialize_for_write)
```

2020-12-01 16:58 UTC, blakemcintyre commented on lib/chartmogul/csv/plan.rb
> +      # https://github.com/chartmogul/platform/blob/main/engines/data_ingestion/app/services/data_ingestion/csv_mapping/plan.rb
We shouldn't have references to internal code in a public repository.

2020-12-01 17:02 UTC, blakemcintyre reviewed
What's the plan for this PR as `'/v2/import/:data_source_uuid` currently does nothing other than return `OK`?

2020-12-01 17:46 UTC, macharmi commented
@blakemcintyre this is on hold for the moment. @viktorchukhantsev is calling directly DataIngestion classes from integrations instead of making an API rest call.
Please let me know if you need it and I can finish it.

2021-12-08 08:24 UTC, closed without merging